// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHhkCOgn-2MZkuvZTpt59aPmhrlm4QVvE',
    appId: '1:364015441324:web:01cdf11b13fe76b6231609',
    messagingSenderId: '364015441324',
    projectId: 'notes-app-58ec9',
    authDomain: 'notes-app-58ec9.firebaseapp.com',
    storageBucket: 'notes-app-58ec9.firebasestorage.app',
    measurementId: 'G-7MMVTP7SDE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAx4jK7iCEv0ceQiHxDBnPnZrHCqm8AM24',
    appId: '1:364015441324:android:174e65b6825891f2231609',
    messagingSenderId: '364015441324',
    projectId: 'notes-app-58ec9',
    storageBucket: 'notes-app-58ec9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJCxi26DA_WEHRiFEK8MdaKky32pqHwAk',
    appId: '1:364015441324:ios:e436960eb4000b35231609',
    messagingSenderId: '364015441324',
    projectId: 'notes-app-58ec9',
    storageBucket: 'notes-app-58ec9.firebasestorage.app',
    iosBundleId: 'com.example.firebaseNotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJCxi26DA_WEHRiFEK8MdaKky32pqHwAk',
    appId: '1:364015441324:ios:e436960eb4000b35231609',
    messagingSenderId: '364015441324',
    projectId: 'notes-app-58ec9',
    storageBucket: 'notes-app-58ec9.firebasestorage.app',
    iosBundleId: 'com.example.firebaseNotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHhkCOgn-2MZkuvZTpt59aPmhrlm4QVvE',
    appId: '1:364015441324:web:373b482057295be1231609',
    messagingSenderId: '364015441324',
    projectId: 'notes-app-58ec9',
    authDomain: 'notes-app-58ec9.firebaseapp.com',
    storageBucket: 'notes-app-58ec9.firebasestorage.app',
    measurementId: 'G-PWHHK234VS',
  );
}
